# Generated by Django 5.0.2 on 2024-02-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=20, unique=True)),
                ('subject', models.CharField(choices=[('Math', 'Mathematics'), ('Sci', 'Science'), ('Eng', 'English'), ('His', 'History')], max_length=16)),
                ('mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
