# Generated by Django 5.0.2 on 2024-02-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='class_year',
            field=models.CharField(choices=[('1', 'I-YEAR'), ('2', 'II-YEAR')], default='1', max_length=16),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('sem1', 'SEMESTER I'), ('sem2', 'SEMESTER II'), ('sem3', 'SEMESTER III'), ('sem4', 'SEMESTER IV')], default='sem1', max_length=16),
        ),
    ]
